### ISSUE TITLE
3T GE 35TE PRESS - TE "unusal value. Expecting a value < 0.5s"

### ISSUE THREAD

**Issue by weberam2** [wtclarke/fsl_mrs#13] opened 2022-07-06 18:04 UTC
Hello!
I have a P file that comes from a 3T GE scanner running a 35TE PRESS sequence

I run the following:

`spec2nii ge P29696.7
fsl_mrs_preproc --output processed --data P29696.nii.gz --reference P29696_ref.nii.gz --report
svs_segment -t T1.nii.gz processed/metab.nii.gz
fsl_mrs  --data metab.nii.gz --basis my_basis_spectra --output example_svs  --h2o wref.nii.gz --tissue_frac segmentation.json --report`

The basis set comes from MRSCloud https://braingps.mricloud.org/mrs-cloud

When I run fsl_mrs, it completes, but ends with: 
"te is an unusal value. Expecting a value < 0.5 s.                                                                                                                               
tr is an unusal value. Expecting a value < 20 s."

And in the report it says under Quantification Information:

"Metabolite T2: | 194.0 ms
Metabolite T1: | 1.29 s
Sequence echo time (TE): | 35000000.0 ms
Sequence repetition time (TR): | 1500000.0 s
Relaxation corrected water concentration: | 0 mmol/kg
Metabolite relaxation correction (1/e(-TE/T2)): | inf
Raw concentration to molarity scaling: | nan
Raw concentration to molality scaling: | nan"

Any ideas? I'm happy to share my P file

**Comment by wtclarke** [comment] 2022-07-07 13:48
Hi @weberam2,

It looks like the TE and TR get interpreted in the wrong units by spec2nii. This isn't entirely surprising as I don't have a huge amount of experience with GE p-files. Is there any chance you could share the file? I'll also take a closer look at the test cases I already have. 

BW

Will

**Comment by wtclarke** [comment] 2022-07-08 09:46
Hi Alex,

This should be fixed as of spec2nii 0.4.6. It's up on pypi now (pip) but will take a few hours to get built and placed on conda-forge (conda).

BW

Will

**Comment by wtclarke** [comment] 2022-07-08 09:47
Closing this issue. Feel free to reopen if the issue isn't fixed.

**Closed by wtclarke** 2022-07-08 09:47 UTC
